### ISSUE TITLE
runsanitytests.bat: not able to load test data

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/py4cytoscape#20]
```
py4cytoscape:~/py4cytoscape/tests$ source runsanitytests.bat 
Into test_create_igraph_from_network()
Out of 'test_create_igraph_from_network'
.Into test_create_network_from_data_frames()
Out of 'test_create_network_from_data_frames'
.Into test_create_network_from_igraph()
Out of 'test_create_network_from_igraph'
.Into test_create_network_from_networkx()
/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/pandas-1.1.3-py3.9-linux-x86_64.egg/pandas/core/frame.py:1485: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(
Out of 'test_create_network_from_networkx'
.Into test_create_networkx_from_network()
/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/pandas-1.1.3-py3.9-linux-x86_64.egg/pandas/core/frame.py:1485: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(
Out of 'test_create_networkx_from_network'
.Into test_import_network_from_file()
In commands_post(): File 'galFiltered.sif' not found:
'test_import_network_from_file' exception CyError("In commands_post(): File 'galFiltered.sif' not found:")
EInto test_open_session()
In commands_post(): File 'Affinity Purification.cys' not found:
'test_open_session' exception CyError("In commands_post(): File 'Affinity Purification.cys' not found:")
E
======================================================================
ERROR: test_import_network_from_file (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.43.99:1234/v1/commands/network/load%20file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 89, in test_import_network_from_file
    res = import_network_from_file('data/galFiltered.sif')
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/networks.py", line 1120, in import_network_from_file
    res = commands.commands_post(f'network load file file="{file}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'galFiltered.sif' not found:

======================================================================
ERROR: test_open_session (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.43.99:1234/v1/commands/session/open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 46, in test_open_session
    self.assertDictEqual(open_session('data/Affinity Purification.cys'), {})
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/session.py", line 114, in open_session
    return commands.commands_post(f'session open {type}="{file_location}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'Affinity Purification.cys' not found:

----------------------------------------------------------------------
Ran 7 tests in 40.096s

FAILED (errors=2)
```

Cytoscape 3.8.1
Java 11.0.6 by AdoptOpenJDK
Mac OS X 10.15.7 - x86_64

Reproducible with the [Docker test env](https://github.com/cytoscape/py4cytoscape/tree/master/docker#development-and-testing).

**Comment by jorgeboucas** [comment]
This is clearly happening because I am running the python code from the container and Cytoscape from the host. It would be nice to throw warnings and skip such tests in case the file can not be found.

**Comment by jorgeboucas** [comment]
I tested it as well, with Cytoscape/3.7.2 running from inside the container:
```
py4cytoscape:~/py4cytoscape/tests$ source runsanitytests.bat 
Into test_create_igraph_from_network()
In commands_post(): File 'Yeast Perturbation.cys' not found:
'test_create_igraph_from_network' exception CyError("In commands_post(): File 'Yeast Perturbation.cys' not found:")
EInto test_create_network_from_data_frames()
Out of 'test_create_network_from_data_frames'
.Into test_create_network_from_igraph()
In commands_post(): File 'Yeast Perturbation.cys' not found:
'test_create_network_from_igraph' exception CyError("In commands_post(): File 'Yeast Perturbation.cys' not found:")
EInto test_create_network_from_networkx()
In commands_post(): File 'Yeast Perturbation.cys' not found:
'test_create_network_from_networkx' exception CyError("In commands_post(): File 'Yeast Perturbation.cys' not found:")
EInto test_create_networkx_from_network()
In commands_post(): File 'Yeast Perturbation.cys' not found:
'test_create_networkx_from_network' exception CyError("In commands_post(): File 'Yeast Perturbation.cys' not found:")
EInto test_import_network_from_file()
In commands_post(): File 'galFiltered.sif' not found:
'test_import_network_from_file' exception CyError("In commands_post(): File 'galFiltered.sif' not found:")
EInto test_open_session()
In commands_post(): File 'Yeast Perturbation.cys' not found:
'test_open_session' exception CyError("In commands_post(): File 'Yeast Perturbation.cys' not found:")
E
======================================================================
ERROR: test_create_igraph_from_network (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:1234/v1/commands/session/open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 105, in test_create_igraph_from_network
    load_test_session()
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 34, in load_test_session
    open_session(session_filename)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/session.py", line 114, in open_session
    return commands.commands_post(f'session open {type}="{file_location}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'Yeast Perturbation.cys' not found:

======================================================================
ERROR: test_create_network_from_igraph (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:1234/v1/commands/session/open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 184, in test_create_network_from_igraph
    load_test_session()
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 34, in load_test_session
    open_session(session_filename)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/session.py", line 114, in open_session
    return commands.commands_post(f'session open {type}="{file_location}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'Yeast Perturbation.cys' not found:

======================================================================
ERROR: test_create_network_from_networkx (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:1234/v1/commands/session/open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 148, in test_create_network_from_networkx
    load_test_session()
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 34, in load_test_session
    open_session(session_filename)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/session.py", line 114, in open_session
    return commands.commands_post(f'session open {type}="{file_location}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'Yeast Perturbation.cys' not found:

======================================================================
ERROR: test_create_networkx_from_network (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:1234/v1/commands/session/open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 123, in test_create_networkx_from_network
    load_test_session()
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 34, in load_test_session
    open_session(session_filename)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/session.py", line 114, in open_session
    return commands.commands_post(f'session open {type}="{file_location}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'Yeast Perturbation.cys' not found:

======================================================================
ERROR: test_import_network_from_file (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:1234/v1/commands/network/load%20file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 96, in test_import_network_from_file
    res = import_network_from_file()
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/networks.py", line 1120, in import_network_from_file
    res = commands.commands_post(f'network load file file="{file}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'galFiltered.sif' not found:

======================================================================
ERROR: test_open_session (test_sanity.SanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 386, in commands_post
    r.raise_for_status()
  File "/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/requests-2.24.0-py3.9.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:1234/v1/commands/session/open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/py4cy/py4cytoscape/test_utils/helpers.py", line 76, in wrapper_entry_exit
    value = func(*args, **kwargs)
  File "/home/py4cy/py4cytoscape/tests/test_sanity.py", line 41, in test_open_session
    self.assertDictEqual(open_session(), {})
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/session.py", line 114, in open_session
    return commands.commands_post(f'session open {type}="{file_location}"', base_url=base_url)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 392, in commands_post
    _handle_error(e)
  File "/home/py4cy/py4cytoscape/py4cytoscape/commands.py", line 678, in _handle_error
    raise e
py4cytoscape.exceptions.CyError: In commands_post(): File 'Yeast Perturbation.cys' not found:

----------------------------------------------------------------------
Ran 7 tests in 28.600s

FAILED (errors=6)
```

**Comment by jorgeboucas** [comment]
running locally did not show any problem:
```
(pycy) laptop:...ontainer/py4cytoscape/tests% source runsanitytests.bat 
Into test_create_igraph_from_network()
Out of 'test_create_igraph_from_network'
.Into test_create_network_from_data_frames()
Out of 'test_create_network_from_data_frames'
.Into test_create_network_from_igraph()
Out of 'test_create_network_from_igraph'
.Into test_create_network_from_networkx()
/Users/jboucas/pycy/lib/python3.8/site-packages/pandas/core/frame.py:1485: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(
Out of 'test_create_network_from_networkx'
.Into test_create_networkx_from_network()
/Users/jboucas/pycy/lib/python3.8/site-packages/pandas/core/frame.py:1485: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(
Out of 'test_create_networkx_from_network'
.Into test_import_network_from_file()
Out of 'test_import_network_from_file'
.Into test_open_session()
Out of 'test_open_session'
.
----------------------------------------------------------------------
Ran 7 tests in 36.097s

OK
```

**Comment by bdemchak** [comment]
There is a lot going on with paths under the covers. This arises from the assumption that Cytoscape is running in one process and the Python kernel is running in another ... each with their idea of "current directory". 

Nearly always, a path in a py4cytoscape workflow is sent to Cytoscape as a full path. For example, if the Python kernel is running in '.../container/py4cytoscape/tests', a call like open_session('my.cys') will be sent to CyREST as the full path '.../container/py4cytoscape/tests/my.cys'. 

The exception to this is the default session and network (e.g., open_session()). That default is passed as 'sampleData/sessions/Yeast Perturbation.cys', and py4cytoscape expects CyREST/Cytoscape to resolve that relative to the current working directory for the Cytoscape process. For installations I'm aware of, that would be the Cytoscape installation directory (which has a sampleData sub-directory). 

It sounds to me like your configuration may not have set the current directory to the Cytoscape installation directory before starting Cytoscape?? 

That would explain an awful lot, though maybe not everything. If I have this right, would you consider changing CWD to the Cytoscape directory and then starting Cytoscape??

**Comment by jorgeboucas** [comment]
- [ ] trace path to files and add it as an argument to the test calls

**Comment by jorgeboucas** [comment]
```
py4cytoscape:~/py4cytoscape/tests$ export TESTS_FOLDER=/Users/jboucas/py4cy-container/py4cytoscape/tests/
py4cytoscape:~/py4cytoscape/tests$ source runsanitytests.bat Into test_create_igraph_from_network()
Out of 'test_create_igraph_from_network'
.Into test_create_network_from_data_frames()
Out of 'test_create_network_from_data_frames'
.Into test_create_network_from_igraph()
Out of 'test_create_network_from_igraph'
.Into test_create_network_from_networkx()
Out of 'test_create_network_from_networkx'
.Into test_create_networkx_from_network()
Out of 'test_create_networkx_from_network'
.Into test_import_network_from_file()
Out of 'test_import_network_from_file'
.Into test_open_session()
Out of 'test_open_session'
.
----------------------------------------------------------------------
Ran 7 tests in 44.287s

OK
```
