### ISSUE TITLE
import_network_from_file fails on some XGMML

### ISSUE THREAD

**Issue by nilsoberg2** [cytoscape/py4cytoscape#71]
For "large" XGMMML files `import_network_from_file` fails with the following message:

`In commands_post(): {'status': 500, 'type': 'urn:cytoscape:ci:cyrest-core:v1:handle-json-command:errors:3', 'message': 'Task returned invalid json.', 'link': 'file:/.../CytoscapeConfiguration/3/framework-cytoscape.log'}`

The network looks fine, however, in the Cytoscape UI.  The `framework-cytoscape.log` file contains the following relevant messages:

`
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 5 column 2
        at com.google.gson.Gson.fromJson(Gson.java:815) ~[!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:770) ~[!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:719) ~[!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:691) ~[!/:?]
        at org.cytoscape.rest.internal.commands.resources.CommandResource.getJSONResponse(CommandResource.java:399) [!/:?]
        at org.cytoscape.rest.internal.commands.resources.CommandResource.buildCIResult(CommandResource.java:287) [!/:?]
        at org.cytoscape.rest.internal.commands.resources.CommandResource.handleJSONCommand(CommandResource.java:268) [!/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [!/:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [!/:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [!/:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [!/:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [!/:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [!/:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [!/:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [!/:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [!/:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [!/:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [!/:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [!/:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [!/:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [!/:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [!/:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [!/:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [!/:?]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) [!/:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) [!/:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) [!/:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) [!/:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) [!/:?]
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76) [!/:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545) [!/:9.4.22.v20191022]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [!/:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296) [!/:9.4.22.v20191022]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:298) [!/:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1562) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [!/:9.4.22.v20191022]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [!/:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.Server.handle(Server.java:500) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:562) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [!/:9.4.22.v20191022]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [!/:9.4.22.v20191022]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.EOFException: End of input at line 5 column 2
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1413) ~[!/:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:484) ~[!/:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:416) ~[!/:?]
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69) ~[!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:805) ~[!/:?]
        ... 70 more
`

Code to reproduce (after loading Cytoscape):

`
import py4cytoscape as py4
ssn_path = "large_ssn.xgmml"
py4.cytoscape_ping()
py4.import_network_from_file(file=ssn_path)
`

As far as I can tell this affects all versions of Cytoscape.

Example input XGMML files are attached.

[small_ssn.zip](https://github.com/cytoscape/py4cytoscape/files/7437457/small_ssn.zip)
[large_ssn.zip](https://github.com/cytoscape/py4cytoscape/files/7437466/large_ssn.zip)

**Comment by bdemchak** [comment]
First, thanks for documenting this so well. I agree with your assumption that the network looks OK. It has the same number of nodes and edges as if it was loaded from the UI.

I don't need py4cytoscape to duplicate this. While py4cytoscape adds a lot of value to CyREST (the Cytoscape REST interface), it's pretty thin in this situation. So, it's just passing the .XGMML to CyREST/Cytoscape and returning whatever CyREST/Cytoscape returns. You can duplicate this, too, in Swagger if you're interested (see below). 

I have seen something like this with this function, and have reported it already as CYTOSCAPE-12772. In my code, I work around it using code like this:

```
from requests import HTTPError
p4c.close_session(False)

try:
  p4c.import_network_from_file('BIOGRID-ORGANISM-Saccharomyces_cerevisiae-3.2.105.mitab')
except:  
  pass
if p4c.get_network_count() != 1:
  raise Exception('Failed to load network')
net_suid = p4c.get_network_suid()
print(f'Network identifier: {net_suid}')
```

Perhaps reporting the problem again will get higher priority for 3.9.1. 

![image](https://user-images.githubusercontent.com/3696094/139556177-9adab3cc-0b49-4f1b-9904-3aaa92e915cb.png)

**Comment by nilsoberg2** [comment]
I misread your comment and submitted a bug report via the main Cytoscape form (I thought you indicated I should submit it).  Sorry about the duplicate bug.  Thanks for getting back to me.

**Comment by bdemchak** [comment]
Absolutely no problem, Nils ... very glad to have your comments and interest. 

FYI, this was discussed at last Thursday's team meeting, and was assigned to a Cytoscape developer. Seems like a natural for Cytoscape 3.9.1 ... we hope.
