### ISSUE TITLE
problem with p4c.set_node_coarder...

### ISSUE THREAD

**Issue by eirinland** [cytoscape/py4cytoscape#77]
Hello! 
When running the commands bellow I receive an error message for both of the p4c.set_node_border functions:
p4c.set_node_color_mapping("Superkingdom",["Archaea", "Bacteria", "Eukaryota", "Viruses"], [green, yellow, purple, blue], mapping_type="d")
**p4c.set_node_border_color_mapping**("AF2 model", ["Yes", "No"], [black, grey])
**p4c.set_node_border_width_mapping**("HasPDB", ["YES", "NO"], [5, 3])
p4c.set_node_shape_mapping("StandardMotif", ["YES", "NO"], ["HEXAGON", "ELLIPSE"])

The set_node_color and set_node_shape works fine, which to me mean that there is something wrong with the functions related to boarders.

**The error message I get**:
In cyrest_post(): Could not create new Mapping.
Traceback (most recent call last):

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/commands.py", line 190, in cyrest_post
    r.raise_for_status()

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:1234/v1/styles/default/mappings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/eirinlandsem/comchem_PhD/ark/py4cs_Eirin.py", line 100, in <module>
    p4c.set_node_border_color_mapping("AF2 model", ["Yes", "No"], [black, grey])

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/style_mappings.py", line 391, in set_node_border_color_mapping
    return _update_visual_property('NODE_BORDER_PAINT', table_column, table_column_values=table_column_values,

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/style_mappings.py", line 2075, in _update_visual_property
    res = update_style_mapping(style_name, mvp, base_url=base_url)

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/style_mappings.py", line 206, in update_style_mapping
    res = commands.cyrest_post(f'styles/{style_name}/mappings', body=[mapping], base_url=base_url,

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/py4cytoscape_logger.py", line 133, in wrapper_log
    log_exception(func, e)

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/py4cytoscape_logger.py", line 130, in wrapper_log
    value = func(*args, **kwargs) # Call function being logged

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/commands.py", line 199, in cyrest_post
    _handle_error(e)

  File "/Users/eirinlandsem/opt/anaconda3/envs/py38traverse/lib/python3.8/site-packages/py4cytoscape/commands.py", line 682, in _handle_error
    raise e

CyError: In cyrest_post(): Could not create new Mapping.

Do you have any idea on how to fix this? :)
Best regards,
Eirin

**Comment by eirinland** [comment]
Well, that is embarrassing, I added the mapping_type argument and it worked. 
I can use this opportunity to say thanks for a great package at least :)
Best regards, 
Eirin

**Comment by bdemchak** [comment]
Hi, eirinland ...

Indeed, I have looked this thread over and I can see where missing the mapping_type parameter would mess things up.

I see that the first two calls set mapping_type to 'd' for discrete mapping, which accomplished your objective.

Omitting the mapping_type in the later calls indicated a 'c' (for continuous) mapping, which is a mismatch for your other parameters. 

I apologize for the API design that led you to this mistake. We'll learn from this.

In the meantime, in case you're not quite comfortable with these mapping types, I can suggest a few sections I have found useful:

http://manual.cytoscape.org/en/stable/Styles.html#how-mappings-work

and 

https://py4cytoscape.readthedocs.io/en/0.0.9/concepts.html#value-generators

Thanks for the kind words about py4cytoscape ... if you have any other questions, please feel free to ask.

Best of luck with using py4cytoscape!
